name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'Formula/**/*.rb'
      - '.github/workflows/*'

  workflow_dispatch:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ANALYTICS: 1

jobs:
  checks:
    name: Checks
    runs-on: macos-15
    steps:
      - name: Setup Homebrew
        id: homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.homebrew.outputs.gems-path }}
          key: ci-rubygems-${{ steps.homebrew.outputs.gems-hash }}
          restore-keys: ci-rubygems-

      - name: Check only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Check tap setup
        run: brew test-bot --only-setup

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
